PATH:
  INPUT: "./raw_txt_input"
  OUTPUT: "./output"
API:
  API_KEY: "YOURAPIKEY"
  BASE_URL: "https://api.together.xyz"
  LOGICAL_MODEL: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
  LARGE_LOGICAL_MODEL: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
SYSTEM:
  USE_FILE_NAMES: False
  ASSISTANT_MODE: False 
  DOUBLE_CHECK_COUNTER: 3
  USE_SUBSET: False
  REARRANGEMENTS_TO_TAKE: 3
  CONCURRENCY_LIMIT: 10