PATH:
  INPUT: "./raw_txt_input"
  OUTPUT: "./output"
  DEFAULT_PROMPTS: "./prompts"
  PROMPTS: "./prompts" # model used in most of the pipeline (everything but conversation generation)
API:
  API_KEY: "78f76c74c714f78f4692f996f457ba87f509d98c78874dc317550fb9c39afeb6"
  BASE_URL: "https://api.together.xyz"
  LOGICAL_MODEL: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
  LARGE_LOGICAL_MODEL: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
SYSTEM:
  USE_FILENAMES: False
  ASSISTANT_MODE: False 
  DOUBLE_CHECK_COUNTER: 3
  USE_SUBSET: True
  REARRANGEMENTS_TO_TAKE: 3
  CONCURRENCY_LIMIT: 90
  COMPLETION_MODE: True # true = /v1/completion false = /v1/chat/compleation
  MODE: "api" # can be one of "api"|"aphrodite"|"llamacpp"