PATH:
  INPUT: "./raw_txt_input"
  OUTPUT: "./output"
API:
  API_KEY: "674df6ce3b6ed1528c710f9507504f98f003b94a936b0c9d4d05e5fe618504d0"
  BASE_URL: "https://api.together.xyz"
  LOGICAL_MODEL: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
  LARGE_LOGICAL_MODEL: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
SYSTEM:
  USE_FILE_NAMES: False
  ASSISTANT_MODE: False 
  DOUBLE_CHECK_COUNTER: 3
  USE_SUBSET: False
  REARRANGEMENTS_TO_TAKE: 3
  CONCURRENCY_LIMIT: 90
  COMPLETION_MODE: True
