API:
  API_KEY: 5316fe488ad994351389cbf07f83508f32987092644a4dcc64573dc725587b18
  BASE_URL: https://api.together.xyz
  LARGE_LOGICAL_MODEL: meta-llama/Llama-3-70b-chat-hf
  LOGICAL_MODEL: meta-llama/Llama-3-8b-chat-hf
  QUANTIZATION_LARGE: gptq
  QUANTIZATION_SMALL: gptq
HUGGINGFACE:
  HUB_PATH: Heralax/test-atk-dataset-do-not-use-3
  PRIVATE: false
  PUSH_TO_HUB: true
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./raw_text_input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASE:
  PHASE_INDEX: 3
  WORK_IN_PHASES: false
SKIP:
  ANSWER_RELEVANCY_CHECK: false
  QUESTION_CHECK: false
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: false
  CONCURRENCY_LIMIT: 50
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between
    a generalist, generic AI assistant, and a human.
  DOUBLE_CHECK_COUNTER: 1
  FINAL_ASSISTANT_PROMPT_NO_RAG: 'You are a helpful AI assistant.

    '
  FINAL_ASSISTANT_PROMPT_RAG: 'You are a helpful AI assistant.


    Context information is below:


    ----------------------

    {data}

    '
  MODE: api
  STOP: true
  SUBSET_SIZE: 10
  USE_FILENAMES: false
  USE_SUBSET: true
